filter:
    excluded_paths:
        - vendor/*            # Exclude any vendor dependencies (if applicable in the future)
        - node_modules/*      # Exclude Node.js dependencies (if added later)
        - .github/*           # Exclude GitHub Actions or other build files
        - tests/*             # Exclude tests (if applicable)
        - .git/*              # Exclude git metadata
        - .scrutinizer.yml    # Exclude this configuration file itself
        - readme.txt          # Exclude the generated readme.txt

build:
    nodes:
        analysis:
            php:
                version: ['8.2', '8.1', '8.0', '7.4']   # Supported PHP versions for WordPress

            before:
                # Before analysis, ensure PHP CodeSniffer and PHP Mess Detector are available
                - if [ ! -f ./vendor/bin/phpcs ]; then echo "Please ensure PHPCS is installed."; fi
                - if [ ! -f ./vendor/bin/phpmd ]; then echo "Please ensure PHPMD is installed."; fi

tools:
    php_analyzer: true            # Enable PHP static analysis
    php_mess_detector:
        config: phpmd.xml         # Use the existing phpmd.xml configuration for PHPMD analysis
    php_code_sniffer:
        config:
            standard: .phpcs.xml.dist  # Use your existing .phpcs.xml.dist for PHPCS configuration
    php_code_coverage:
        enabled: false            # No PHPUnit, so code coverage reporting is disabled
    eslint:
        enabled: true            # Enable JavaScript linting with ESLint (if applicable)
        config: .eslintrc.json    # You can specify your ESLint config file here
    js_hint:
        enabled: true            # Enable JS Hint for analyzing JavaScript code
    javascript: true               # Enable general JavaScript static analysis (if JS is added later)

checks:
    php:
        security_vulnerabilities: true   # Detect potential security vulnerabilities
        no_global_scope: true            # Avoid global scope in PHP
        unused_variables: true           # Warn about unused variables
        duplication: true                # Detect duplicated code
        to_do_comments: true             # Warn about TODO/FIXME comments in code

    javascript:
        no_implicit_any: true            # Avoid implicit `any` type in JavaScript (for TypeScript or JS)

coding_style:
    php:
        spaces:
            indent_with_spaces: true     # Enforce spaces (not tabs)
            line_length: 120             # Set max line length to 120 characters
