filter:
    excluded_paths:
        - vendor/*
        - node_modules/*
        - .github/*
        - tests/*
        - .git/*
        - .scrutinizer.yml
        - readme.txt

build:
    nodes:
        analysis:
            php:
                version: ['8.2', '8.1', '8.0', '7.4']   # Supported PHP versions

            before:
                # Ensure PHP CodeSniffer and PHP Mess Detector are available
                - if [ ! -f ./vendor/bin/phpcs ]; then echo "Please ensure PHPCS is installed."; fi
                - if [ ! -f ./vendor/bin/phpmd ]; then echo "Please ensure PHPMD is installed."; fi

tools:
    php_analyzer: true            # Enable PHP static analysis
    php_mess_detector:
        config: phpmd.xml         # Link to your provided phpmd.xml file
    php_code_sniffer:
        config:
            standard: .phpcs.xml.dist  # Link to your provided .phpcs.xml.dist configuration
    external_code_coverage: false      # No code coverage for now (since PHPUnit isn't used)
    eslint:
        enabled: true            # Enable JavaScript linting with ESLint
        config: .eslintrc.json    # Reference your ESLint config (if available)
    js_hint:
        enabled: true            # Enable JS Hint for JavaScript code analysis
    javascript: true               # Enable general JavaScript static analysis

checks:
    php:
        security_vulnerabilities: true   # Detect potential security vulnerabilities
        no_global_scope: true            # Avoid global scope in PHP
        unused_variables: true           # Warn about unused variables
        duplication: true                # Detect duplicated code
        to_do_comments: true             # Warn about TODO/FIXME comments in code

    javascript:
        no_implicit_any: true            # Avoid implicit `any` type in JavaScript (for TypeScript or JS)

coding_style:
    php:
        spaces:
            indent_with_spaces: true     # Enforce spaces instead of tabs
            line_length: 120             # Set max line length to 120 characters
