name: Deploy to WordPress SVN

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Subversion
        run: sudo apt-get install subversion

      - name: Deploy to WordPress SVN
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
        run: |
          svn co https://plugins.svn.wordpress.org/cmb2-admin-extension/ svn-dir
          rsync -av --delete --exclude=".git" ./ svn-dir/trunk/
          cd svn-dir
          svn add --force trunk/*
          svn commit -m "Deploying version ${{ github.ref }}" --username $SVN_USERNAME --password $SVN_PASSWORD --non-interactive
