name: Deploy to WordPress SVN

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Install Subversion
      - name: Install Subversion
        run: sudo apt-get install subversion

      # Step 3: Generate readme.txt using the script in .github/scripts/
      - name: Generate readme.txt
        run: .github/scripts/generate-readme.sh

      # Step 4: Deploy to WordPress SVN /trunk/
      - name: Deploy to WordPress SVN /trunk/
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
        run: |
          svn co https://plugins.svn.wordpress.org/cmb2-admin-extension/ svn-dir
          rsync -av --delete --exclude=".git" ./ svn-dir/trunk/
          cd svn-dir
          svn add --force trunk/*
          svn commit -m "Deploying version ${{ github.ref }}" --username $SVN_USERNAME --password $SVN_PASSWORD --non-interactive

      # Step 5: Create a tag in WordPress SVN /tags/
      - name: Create SVN Tag
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
        run: |
          VERSION=${GITHUB_REF/refs\/tags\/v/}
          svn cp https://plugins.svn.wordpress.org/cmb2-admin-extension/trunk https://plugins.svn.wordpress.org/cmb2-admin-extension/tags/$VERSION -m "Tagging version $VERSION" --username $SVN_USERNAME --password $SVN_PASSWORD --non-interactive
